services:
  rabbitmq:
    image: rabbitmq:management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "15672:15672" # RabbitMQ Management UI
      - "5672:5672"   # RabbitMQ AMQP
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - nginx
networks:
  nginx:
    name: nginx
    external: true
volumes:
  rabbitmq-data: