services:
  jenkins:
    # dev/secret123
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - nginx
  jenkins-agent1:
    image: jenkins/agent
    container_name: jenkins-agent1
    init: true
    environment:
      - JENKINS_URL=http://jenkins:8080
    # create agent1 on jenkins management site, the remote directory should fill with /home/jenkins/agent
    volumes:
      - agent1-workdir:/home/jenkins/agent
      - ./jenkins-secret:/home/jenkins/jenkins-secret
    # secret will show after you create agent in jenkins control panel
    command: java -jar /usr/share/jenkins/agent.jar -url http://jenkins:8080/ -secret @/home/jenkins/jenkins-secret -name agent1 -webSocket -workDir /home/jenkins/agent
    networks:
      - nginx
networks:
  nginx:
    name: nginx
    external: true
volumes:
  jenkins_home:
  agent1-workdir:
