services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - nginx
  agent1:
    image: jenkins/agent
    container_name: agent1
    init: true
    environment:
      - JENKINS_URL=http://jenkins:8080
    volumes:
      - agent1-workdir:/home/jenkins/agent
    # secret will show after you create agent in jenkins control panel
    command: java -jar /usr/share/jenkins/agent.jar -url http://jenkins:8080/ -secret 748fadd29dd4b366c6c1ed9cddee0d3047427793ce21b21167f1f1faaaafb8d1 -name agent1 -workdir /home/jenkins/agent
    networks:
      - nginx
networks:
  nginx:
    name: nginx
    external: true
volumes:
  jenkins_home:
  agent1-workdir:
