services:
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: dev
      MYSQL_USERNAME: dev
      MYSQL_PASSWORD: secret123
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - nginx
networks:
  nginx:
    external: true
volumes:
  mysql-data:
