ALTER USER 'root'@'%' IDENTIFIED BY 'secret123';
CREATE USER 'dev'@'%' IDENTIFIED BY 'secret123';

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'dev'@'%' WITH GRANT OPTION;

CREATE DATABASE IF NOT EXISTS dev;
